on:
  push:
    branches:
      - main

name: CI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install minimal nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly

      - name: Build and Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features

      - name: Build WebAssembly
        run: |
          cd docs
          cargo install wasm-pack
          wasm-pack build --target web --out-dir static --out-name compy_wasm
          rm static/.gitignore

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: docs/
